  [build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Explicitly set these for the production environment
[context.production.environment]
  SITE_ID = "ba1416c8-1ad6-4d18-9798-83a21c23399b"
  NETLIFY_BLOB_TOKEN = "nfp_6DU6kiqu5fDJxtLWzoePzjgwQVEFJVMWf324"
